# -*- coding: utf-8 -*-
"""24th python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVDYbAUppd5x_GAb48OJFgbS8nVkdzBV
"""

import pandas as pd
df = pd.read_csv(r'./sample_data/california_housing_train.csv')

# to convert list to series in pandas

number = [1,2,3,4,5,6]

number_series = pd.Series(number)

print(number_series)

df.head(10)

df.tail()

df.describe()

df.info()

df.drop("longitude",axis=1,inplace=True)

print(df)

df.drop(0,axis='index')

print (df)

df.drop(2,axis='index',inplace=True)

print(df)

df.rename(columns={'latitude':'lat'},inplace=True)

print(df)

def custom(no):
 no=no*no
 return no

custom(6)

df.groupby(by='population').mean()

df.shape

df.agg('sum')

df.mean()

df.median()

df.corr()

df['lat'].value_counts()

df1=pd.read_csv(r'/content/sample_data/california_housing_train.csv')

print(df1)

df.merge(df1,left_on='lat',right_on='latitude')