# -*- coding: utf-8 -*-
"""Basics of Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qgLnT3QoNLNKUfdNdexoLzaGPSPKQYv7
"""

x=10

print(x)

#whatever you write in a comment is not executed.
# This is just for your own reference

# Windows/linux: Ctrl + /
# Mac: Cmd + /

def function_name():
  y=6
  z=1
  x=9
  print(x,y,z)

x=10
print(x)

function_name()

# write a comment here
x=10
# integer data type

print(type(x))

y="name"

print(y)

print(type(y))

y='name'

print(y)

print(type(y))

z=1.1

print(z)

print(type(z))

def function():
  variable_a='this is inside function'
  print(variable_a)

variable_b='this is outside function'

function()

a=True

print(a)

print(type(a))

# 'str'-> 'string data type'
# 'int'-> 'integer data type'
# 'float'->'float data type'
# 'bool'-> 'boolean data type'

name='Alex'
age="10"
about=''' jdaf;jdjdafhfajdjlajfhdjadf
djaklsj;dajs
dfklafjldfj
asdjldjfl
jlafjldf
jldfjladfj'''

first=10
second=20

print(first+second)

print(first-second)

print(first*second)

print(first/second)

print(first**second)

# 10^20

print(first%second)

first//second

20//3

20/3

first==10

first==29

# and, or, not

# ==, >=, <=, <, >

first==10

first>10

first>=10

first<=10

first<10

first==10 and first==20

first==10 and second==20



first==10 or first==20 or second==30

first==10 and second==20 and first==30

not first==10

first==10

first !=10

shopping=[1,2,3,4,5,6,7,8,9,0]

shopping

3 in shopping

3 not in shopping

# 1. Check all the rules for creating identifiers in python
# 2. Find all the keywords in python
# 3. Read about all the bitwise operators in python and practice
# it in notebook

# int -> integer: 1, 2,-1,-2......

string_name='apple'
list_name=['a','p','p','l','e']

string_name='fjfj'
list_name.append('mango')

string_name

list_name

