# -*- coding: utf-8 -*-
"""python functions 23rd nov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2pirYWZh8O5qO0amxJLbZSn2QvVadpU
"""

age = int (input("typeyourage"))

if age>0 and age<18:
  print("under aged")
elif age>=18 and age<=24:
  print("teenager")
elif age>=25 and age<=35:
  print("man")
elif age>=36 and age<=60:
  print("uncle")
else:
  print("invalid entry")

score = int (input("type score"))

if score>=90 and score<=100:
  print("grade A")
elif score>=80 and score<=89:
  print("grade B")
elif score>=50 and score<=79:
  print("grade C")
elif score>=35 and score<=49:
  print("grade D")
elif score>=0 and score<=34:
  print("failed")
else:
  print("invalid entry")

scores=[15,12,14,16,18,17,12,10]
for score in scores:
  print(score)

scores=[15,135,98,75,88,65,85,158]
for score in scores:
 if score>=90 and score<=100:
  print(score,"grade A")
 elif score>=80 and score<=89:
  print(score,"grade B")
 elif score>=50 and score<=79:
  print(score,"grade C")
 elif score>=35 and score<=49:
  print(score,"grade D")
 elif score>=0 and score<=34:
  print(score,"failed")
 else:
  print(score,"invalid entry")

for number in range(50):
  print(number)

for number in range(1,50):
  print(number)

for number in range(0,56,5):
  print(number)

final_no=50
no=0
while no<final_no:
  print(no)
  no+=1

balance = 300
while balance>0:
  balance=balance-50
  print("newbalance",balance)

final_no=50
no=0
while no<final_no:
  no+=1
  print(no)
  if no==10:
   break

final_no=50
no=0
while no<final_no:
  no+=1
  if no==10:
    continue
  print(no)

no = 0
def pass_example():
  pass
print(no)

age_list = [12, 15, 18, 25, 28, 35, 40, 60]

age.append(88)

age

age[2]

score_tuple = (90, 98, 76, 35, 99)
score_tuple[2]

rank_set = {9,10,6,2,1,7,7,7,7}

rank_set.update({5})

list(rank_set )[2]

rank_set.update({4})
rank_set

fruits = {"mango" : 98,"apple" : 95, "banana":85}
fruits["mango"]
fruits["pineapple"] = 100
fruits["guava"] =80

fruits

print(len(age))

number = (1,2,3,4,5)
print(sum(number))

sum(number)/len(number)

order = [78,34,98,1,56,10,25,85]
order.sort()
print(order)

roll = [("sam",1),("tom",5),("ben",2)]
roll.sort(key=lambda roll : roll[1])
print(roll)

try:
 1/0
except ZeroDivisionError:
  print("divison by zero is not possible")

