# -*- coding: utf-8 -*-
"""python 16 nov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQsXM7pvwCcthyrPJG8Dnr3XKL4-AiZf
"""

x=10
print(x)

def add():
    x=10
    y=10.1
    z=x+y
    print(z)

add()

y=20.1
print (type (y))

a="true"
print(a)
print (type(a))

T=True
print (type(T))

about = ''' the name is rADSE'''
print(about)

D=7
H=10
print(D+H)
print(D-H)
print(D*H)
print(D/H)
print(D%H)
print(D**H)
print(D//H)

print(D==H)
print(D!=H)
print(D>H)
print(D<H)
print(D>=H)
print(D<=H)

D==7 and H==10

D==7 or H==11