# -*- coding: utf-8 -*-
"""Python Data Structures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13P9FUmQi50OqpAdTJo_8MHhgrb2dB8XU
"""

# if the age is less than 18 -> not adult
# if the age is more than 18 -> adult

age=int(input('Type you age: '))

print(age)

print(type(age))

if age <18 and age>=0: # age should be between 0 to 18
  print('not adult')
elif age>=18 and age<=150: # age should be between 18 to 150
  print('adult')
elif age==19:
  print('age is 19')
else: # age is either less than 0 or more than 150
  print('incorrect input')

# exam grade assignment
# conditions are
# grade a for students with score of 90 or more
# grade b for students with score of 80 to 90
# grade c for studnets with score of 70 to 80
# otherwise the student is failed.

# assigning grade to 100 students

scores=[15,18,35,16,90,65,42,57,87,12]

for score in scores:
  if score >=90:
    print(score, 'grade a')
  elif score>=80:
    print(score, 'grade b')
  elif score >=70:
    print(score, 'grade c')
  else:
    print(score, 'failed')

for number in range(50):
  print(number)

# for loop is used till a particular range or the elements of a list
# while loop is used till a particular condition is true.

no+=1 -> no=no+1

final_no=50
no=0
while no<final_no: # check 0<50: True
  no+=1 # no will become 1 from 0
  print(no) #print 1
  if no==10:
    break #break or exit the loop

final_no=50
no=0
while no<final_no: # check 0<50: True
  no+=1 # no will become 1 from 0
  if no==10:
      continue #skip the loop for one iteration
  print(no) #print 1

final_no=50
no=0
def pass_example():
  pass
print(no)

age=[1,2,3,4,5,6,'a','b','c',1.1,1.2,4,4,4,4,4,5,6,6]

age.append(4)

print(age)

age_tuple=(1,2,3,4,5,6,'a','b','c',1.1,1.2,4,4,4,4,4,5,6,6)

age_tuple.append(4)

age_set={1,2,3,4,5,6,'a','b','c',1.1,1.2,4,4,4,4,4,5,6,6}

age_set

# for declaring
# list = []
# set= {}
# tuple = ()

# for accessing elements of list and tuple
# []

fruits_water={'apple':86, 'mango':92,'banana':56}

fruits_water['mango']

age[10]

list(age_set)[5]

list(age_set)

age_set[5]

age_tuple[5]

fruits_water['pineapple']=20

fruits_water

# check all the important functions for list, set, tuple and dictionary

print(fruits_water)

print(len(age_tuple))

number=[6,2,4,5,16,6,6,6,4,25,46,26]

print(sum(number))

print(max(number))

sum(number)/len(number)

number.sort()

print(number)

students=[('a',4),('d',2),('c',9)]

students.sort(key=lambda student: student[1])

print(students)

def classes(class_name,roll_no, student_name='apple'):
  print(class_name,roll_no, student_name)

classes('v',student_name='mango',roll_no=10)

# for student in students:
#   classes('v',student_name='mango',roll_no=student)

a=1
b=0

try:
  a/b
except ZeroDivisionError:
  print('division by 0 is not possible')
except:
  print('error')

# bitwise operators

number_1=6
number_2=5
result=number_1 & number_2
print(bin(number_1), bin(number_2),bin(result))

1,1 ->1
1,0 ->0
0,1 ->0
0,0 ->0

number_1=6
number_2=5
result=number_1 | number_2
print(bin(number_1), bin(number_2),bin(result))

1,1/0,1/1,0->1
0,0 ->0